### ISSUE TITLE
ReferenceError: exports is not defined source-map.js:6:1

### ISSUE THREAD

**Issue by ghovmand** [stacktracejs/stackframe#7]
I install with bower install stacktrace-js
When running app. in the console I get
`ReferenceError: exports is not defined source-map.js:6:1`

**Comment by oliversalzburg** [comment]
What file are you including in your application?

**Comment by ghovmand** [comment]
Thanks for the feedback

<script src="../bower_components/stackframe/stackframe.js"></script>
<script src="../bower_components/error-stack-parser/error-stack-parser.js"></script>
<script src="../bower_components/stack-generator/stack-generator.js"></script>
<script src="../bower_components/source-map/source-map.js"></script>
<script src="../bower_components/stacktrace-gps/dist/stacktrace-gps.js"></script>
<script src="../bower_components/stacktrace-js/dist/stacktrace.js"></script>

**Comment by ghovmand** [comment]
`
<script src="../bower_components/stackframe/stackframe.js"></script>
 <script src="../bower_components/error-stack-parser/error-stack-parser.js"></script>
 <script src="../bower_components/stack-generator/stack-generator.js"></script>
 <script src="../bower_components/source-map/source-map.js"></script>
 <script src="../bower_components/stacktrace-gps/dist/stacktrace-gps.js"></script>
 <script src="../bower_components/stacktrace-js/dist/stacktrace.js"></script>
`

**Comment by ghovmand** [comment]
../bower_components/stackframe/stackframe.js
../bower_components/error-stack-parser/error-stack-parser.js
../bower_components/stack-generator/stack-generator.js
../bower_components/source-map/source-map.js
../bower_components/stacktrace-gps/dist/stacktrace-gps.js
../bower_components/stacktrace-js/dist/stacktrace.js

**Comment by ghovmand** [comment]
I don't get the error in Edge but in Chrome and Firefox I get it....

**Comment by oliversalzburg** [comment]
Please try only including `bower_components/stacktrace-js/dist/stacktrace-with-polyfills.min.js`

**Comment by eriwen** [comment]
Due to how SourceMap is written, it *must* be built using something like webpack and cannot be independently included. 

As @oliversalzburg said, please use one of the `dist/stacktrace.min.js` files

**Comment by stefan--** [comment]
@eriwen I suggest that you include something like 
```
  "main": [
    "dist/stacktrace.min.js",
  ],
```
in your project's `bower.json`. It does not solve the source-map problem, but at least makes sure that only the minified stacktrace-js version is used by build tools.

**Comment by stefan--** [comment]
@eriwen I not only had to change the `main` entry in the `stacktrace.js/bower.json` to `dist/stacktrace-with-polyfills.min.js` but also remove all dependencies from it. Otherwise, when wiring my dependencies (with wiredep) they would be included and thus break the build. 

Not the file looks like this:

```
{
    "name": "stacktrace-js",
    "main": "./dist/stacktrace-with-polyfills.min.js",
    "homepage": "https://github.com/stacktracejs/stacktrace.js",
    "authors": [
        "Eric Wendelin <me@eriwen.com> (http://www.eriwen.com)",
        "Victor Homyakov <vkhomyackov@gmail.com> (https://github.com/victor-homyakov)",
        "Oliver Salzburg (https://github.com/oliversalzburg)"
    ],
    "description": "Turns partial code location into precise code location",
    "moduleType": [
        "amd",
        "globals",
        "node"
    ],
    "keywords": [
        "stacktrace",
        "stack-trace",
        "backtrace",
        "cross-browser",
        "framework-agnostic",
        "error",
        "debugger"
    ],
    "license": "Public Domain",
    "ignore": [
        "**/.*",
        "node_modules",
        "spec"
    ]
}
```

**Comment by LukeSkyw** [comment]
I am not sure why this issue was closed. It is a real issue. When you use wiredep or bower_concat you suppose that your bower components are properly formed to be loaded in the browser.
I should not have to change stacktrace.js bower file for this...
Let me know if I'm wrong.

**Comment by oliversalzburg** [comment]
Related: https://github.com/stacktracejs/stacktrace.js/pull/161

**Comment by eriwen** [comment]
I've merged the referenced PR and updated the bower config to include dependencies so that this issue should be fixed. 

Sorry about the premature closure, that was a mistake on my part.

**Comment by oliversalzburg** [comment]
@eriwen If I'm not mistaken, when using the `concat` version as the `main`, then no dependencies should be declared. Otherwise they will be included by bower, even though they are already merged into the `concat` version.

That being said, I think that `stacktrace-with-promises-and-json-polyfills.js` should be the `main` and no dependencies should be declared at all.

For npm I usually prefer to go as modular as possible, for bower, I prefer the opposite (even though the documentation says otherwise), because the module system in npm is defined much clearer.

Maybe @ghovmand has some input as well?

**Comment by XAMelleOH** [comment]
I'm agree with @oliversalzburg - dependencies should be removed. Just tested on my project with 1.1.1 version - and `exports not found` still presented. If I remove all dependencies - everything works as needed.

**Comment by eriwen** [comment]
FYI v1.1.2 was released on May 3 with this change.
